// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AuthorisationSummaryRow
    {
        /// <summary>
        /// Initializes a new instance of the AuthorisationSummaryRow class.
        /// </summary>
        public AuthorisationSummaryRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AuthorisationSummaryRow class.
        /// </summary>
        public AuthorisationSummaryRow(string product = default(string), string corporateId = default(string), string corporate = default(string), string mid = default(string), System.DateTime? date = default(System.DateTime?), string cardType = default(string), int? authCount = default(int?), int? declineCount = default(int?))
        {
            Product = product;
            CorporateId = corporateId;
            Corporate = corporate;
            Mid = mid;
            Date = date;
            CardType = cardType;
            AuthCount = authCount;
            DeclineCount = declineCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product")]
        public string Product { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardType")]
        public string CardType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authCount")]
        public int? AuthCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "declineCount")]
        public int? DeclineCount { get; set; }

    }
}
