// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AuthorisationBreakdownSummaryRow
    {
        /// <summary>
        /// Initializes a new instance of the AuthorisationBreakdownSummaryRow
        /// class.
        /// </summary>
        public AuthorisationBreakdownSummaryRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AuthorisationBreakdownSummaryRow
        /// class.
        /// </summary>
        public AuthorisationBreakdownSummaryRow(string product = default(string), string corporateId = default(string), string corporate = default(string), string mid = default(string), string cardType = default(string), string responseCode = default(string), string responseCodeDescription = default(string), int? count = default(int?), System.DateTime? transactionDate = default(System.DateTime?))
        {
            Product = product;
            CorporateId = corporateId;
            Corporate = corporate;
            Mid = mid;
            CardType = cardType;
            ResponseCode = responseCode;
            ResponseCodeDescription = responseCodeDescription;
            Count = count;
            TransactionDate = transactionDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product")]
        public string Product { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardType")]
        public string CardType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responseCode")]
        public string ResponseCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responseCodeDescription")]
        public string ResponseCodeDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionDate")]
        public System.DateTime? TransactionDate { get; set; }

    }
}
