// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CardTypeBreakdownRow
    {
        /// <summary>
        /// Initializes a new instance of the CardTypeBreakdownRow class.
        /// </summary>
        public CardTypeBreakdownRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CardTypeBreakdownRow class.
        /// </summary>
        public CardTypeBreakdownRow(string product = default(string), string corporateId = default(string), string corporate = default(string), string binCountry = default(string), string cardType = default(string), int? capturePaymentCount = default(int?))
        {
            Product = product;
            CorporateId = corporateId;
            Corporate = corporate;
            BinCountry = binCountry;
            CardType = cardType;
            CapturePaymentCount = capturePaymentCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product")]
        public string Product { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "binCountry")]
        public string BinCountry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardType")]
        public string CardType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capturePaymentCount")]
        public int? CapturePaymentCount { get; set; }

    }
}
