// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DashboardPaymentMethodRow
    {
        /// <summary>
        /// Initializes a new instance of the DashboardPaymentMethodRow class.
        /// </summary>
        public DashboardPaymentMethodRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DashboardPaymentMethodRow class.
        /// </summary>
        public DashboardPaymentMethodRow(string paymentMethod = default(string), int? count = default(int?))
        {
            PaymentMethod = paymentMethod;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethod")]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
