// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HubSummaryDetailRow
    {
        /// <summary>
        /// Initializes a new instance of the HubSummaryDetailRow class.
        /// </summary>
        public HubSummaryDetailRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HubSummaryDetailRow class.
        /// </summary>
        public HubSummaryDetailRow(string product = default(string), int? count = default(int?), string corporateId = default(string), string corporate = default(string))
        {
            Product = product;
            Count = count;
            CorporateId = corporateId;
            Corporate = corporate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product")]
        public string Product { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

    }
}
