// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Hub.Transactions.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PagedResultAuthorisationByCountrySummaryRow
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PagedResultAuthorisationByCountrySummaryRow class.
        /// </summary>
        public PagedResultAuthorisationByCountrySummaryRow() { }

        /// <summary>
        /// Initializes a new instance of the
        /// PagedResultAuthorisationByCountrySummaryRow class.
        /// </summary>
        public PagedResultAuthorisationByCountrySummaryRow(IList<AuthorisationByCountrySummaryRow> rows = default(IList<AuthorisationByCountrySummaryRow>), long? count = default(long?), long? totalCount = default(long?), long? page = default(long?), long? pageCount = default(long?), long? pageSize = default(long?))
        {
            Rows = rows;
            Count = count;
            TotalCount = totalCount;
            Page = page;
            PageCount = pageCount;
            PageSize = pageSize;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rows")]
        public IList<AuthorisationByCountrySummaryRow> Rows { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long? Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalCount")]
        public long? TotalCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "page")]
        public long? Page { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pageCount")]
        public long? PageCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pageSize")]
        public long? PageSize { get; set; }

    }
}
