// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PaymentMethodBreakdownRow
    {
        /// <summary>
        /// Initializes a new instance of the PaymentMethodBreakdownRow class.
        /// </summary>
        public PaymentMethodBreakdownRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentMethodBreakdownRow class.
        /// </summary>
        public PaymentMethodBreakdownRow(string paymentMethod = default(string), string currency = default(string), string globalProperty = default(string), string globalId = default(string), string bank = default(string), string bankID = default(string), string corporate = default(string), string corporateId = default(string), string merchant = default(string), string merchantID = default(string), string mid = default(string), int? captureCount = default(int?), double? captureCountPercentage = default(double?), double? captureValue = default(double?), double? captureValuePercentage = default(double?), double? averageValue = default(double?), string binCountry = default(string))
        {
            PaymentMethod = paymentMethod;
            Currency = currency;
            GlobalProperty = globalProperty;
            GlobalId = globalId;
            Bank = bank;
            BankID = bankID;
            Corporate = corporate;
            CorporateId = corporateId;
            Merchant = merchant;
            MerchantID = merchantID;
            Mid = mid;
            CaptureCount = captureCount;
            CaptureCountPercentage = captureCountPercentage;
            CaptureValue = captureValue;
            CaptureValuePercentage = captureValuePercentage;
            AverageValue = averageValue;
            BinCountry = binCountry;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethod")]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "global")]
        public string GlobalProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "globalId")]
        public string GlobalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bank")]
        public string Bank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bank_ID")]
        public string BankID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchant")]
        public string Merchant { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantID")]
        public string MerchantID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "captureCount")]
        public int? CaptureCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "captureCountPercentage")]
        public double? CaptureCountPercentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "captureValue")]
        public double? CaptureValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "captureValuePercentage")]
        public double? CaptureValuePercentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "averageValue")]
        public double? AverageValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "binCountry")]
        public string BinCountry { get; set; }

    }
}
