// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PointsInstallmentsDetailsRow
    {
        /// <summary>
        /// Initializes a new instance of the PointsInstallmentsDetailsRow
        /// class.
        /// </summary>
        public PointsInstallmentsDetailsRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PointsInstallmentsDetailsRow
        /// class.
        /// </summary>
        public PointsInstallmentsDetailsRow(string points = default(string), string payNumberMonths = default(string), string installmentType = default(string), string payLaterMonths = default(string))
        {
            Points = points;
            PayNumberMonths = payNumberMonths;
            InstallmentType = installmentType;
            PayLaterMonths = payLaterMonths;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "points")]
        public string Points { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payNumberMonths")]
        public string PayNumberMonths { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "installmentType")]
        public string InstallmentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payLaterMonths")]
        public string PayLaterMonths { get; set; }

    }
}
