// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductSummaryRow
    {
        /// <summary>
        /// Initializes a new instance of the ProductSummaryRow class.
        /// </summary>
        public ProductSummaryRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductSummaryRow class.
        /// </summary>
        public ProductSummaryRow(string globalId = default(string), string globalProperty = default(string), string bankId = default(string), string bank = default(string), string corporateId = default(string), string corporate = default(string), string merchantId = default(string), string mid = default(string), string product = default(string), string transactionType = default(string), int? count = default(int?), string paymentMethod = default(string))
        {
            GlobalId = globalId;
            GlobalProperty = globalProperty;
            BankId = bankId;
            Bank = bank;
            CorporateId = corporateId;
            Corporate = corporate;
            MerchantId = merchantId;
            Mid = mid;
            Product = product;
            TransactionType = transactionType;
            Count = count;
            PaymentMethod = paymentMethod;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "globalId")]
        public string GlobalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "global")]
        public string GlobalProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bankId")]
        public string BankId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bank")]
        public string Bank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantId")]
        public string MerchantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product")]
        public string Product { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionType")]
        public string TransactionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethod")]
        public string PaymentMethod { get; set; }

    }
}
