// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RefundRatesRow
    {
        /// <summary>
        /// Initializes a new instance of the RefundRatesRow class.
        /// </summary>
        public RefundRatesRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RefundRatesRow class.
        /// </summary>
        public RefundRatesRow(string product = default(string), string corporateId = default(string), string corporate = default(string), string mid = default(string), string currency = default(string), string cardType = default(string), double? settlementAmount = default(double?), int? settlementCount = default(int?), double? refundAmount = default(double?), int? refundCount = default(int?), double? exchangeRate = default(double?), double? exchangeAmount = default(double?), string exchangeCurrency = default(string))
        {
            Product = product;
            CorporateId = corporateId;
            Corporate = corporate;
            Mid = mid;
            Currency = currency;
            CardType = cardType;
            SettlementAmount = settlementAmount;
            SettlementCount = settlementCount;
            RefundAmount = refundAmount;
            RefundCount = refundCount;
            ExchangeRate = exchangeRate;
            ExchangeAmount = exchangeAmount;
            ExchangeCurrency = exchangeCurrency;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product")]
        public string Product { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardType")]
        public string CardType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "settlementAmount")]
        public double? SettlementAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "settlementCount")]
        public int? SettlementCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "refundAmount")]
        public double? RefundAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "refundCount")]
        public int? RefundCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exchangeRate")]
        public double? ExchangeRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exchangeAmount")]
        public double? ExchangeAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exchangeCurrency")]
        public string ExchangeCurrency { get; set; }

    }
}
