// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RFIDetailsRow
    {
        /// <summary>
        /// Initializes a new instance of the RFIDetailsRow class.
        /// </summary>
        public RFIDetailsRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RFIDetailsRow class.
        /// </summary>
        public RFIDetailsRow(string recordType = default(string), System.DateTime? rfiRequestedDate = default(System.DateTime?), System.DateTime? deadlineDate = default(System.DateTime?), string addressee = default(string), string caseNumber = default(string), string cardNumber = default(string), string cardExpiry = default(string), string acRef = default(string), System.DateTime? transactionDate = default(System.DateTime?), System.DateTime? transactionTime = default(System.DateTime?), string transactionAmount = default(string), string currency = default(string), string typeOfTransaction = default(string), string merchantName = default(string), string merchantLocation = default(string), string merchantCountry = default(string), string merchantStoreNumber = default(string), string facilityNrAndTerminal = default(string), string authCode = default(string), string rrn = default(string))
        {
            RecordType = recordType;
            RfiRequestedDate = rfiRequestedDate;
            DeadlineDate = deadlineDate;
            Addressee = addressee;
            CaseNumber = caseNumber;
            CardNumber = cardNumber;
            CardExpiry = cardExpiry;
            AcRef = acRef;
            TransactionDate = transactionDate;
            TransactionTime = transactionTime;
            TransactionAmount = transactionAmount;
            Currency = currency;
            TypeOfTransaction = typeOfTransaction;
            MerchantName = merchantName;
            MerchantLocation = merchantLocation;
            MerchantCountry = merchantCountry;
            MerchantStoreNumber = merchantStoreNumber;
            FacilityNrAndTerminal = facilityNrAndTerminal;
            AuthCode = authCode;
            Rrn = rrn;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recordType")]
        public string RecordType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rfiRequestedDate")]
        public System.DateTime? RfiRequestedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deadlineDate")]
        public System.DateTime? DeadlineDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressee")]
        public string Addressee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "caseNumber")]
        public string CaseNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardNumber")]
        public string CardNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardExpiry")]
        public string CardExpiry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "acRef")]
        public string AcRef { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionDate")]
        public System.DateTime? TransactionDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionTime")]
        public System.DateTime? TransactionTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionAmount")]
        public string TransactionAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "typeOfTransaction")]
        public string TypeOfTransaction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantName")]
        public string MerchantName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantLocation")]
        public string MerchantLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantCountry")]
        public string MerchantCountry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantStoreNumber")]
        public string MerchantStoreNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facilityNrAndTerminal")]
        public string FacilityNrAndTerminal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authCode")]
        public string AuthCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rrn")]
        public string Rrn { get; set; }

    }
}
