// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ShippingServiceItemDetailsRow
    {
        /// <summary>
        /// Initializes a new instance of the ShippingServiceItemDetailsRow
        /// class.
        /// </summary>
        public ShippingServiceItemDetailsRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ShippingServiceItemDetailsRow
        /// class.
        /// </summary>
        public ShippingServiceItemDetailsRow(string itemId = default(string), string productId = default(string), string consignmentId = default(string), string barCodeId = default(string), string totalCost = default(string), string totalTax = default(string), string itemStatus = default(string), string itemCode = default(string), string articleId = default(string), string productName = default(string), string estimatedDelivery = default(string), string leavePackage = default(string), string signatureRequired = default(string), string totalBundledCost = default(string), string totalBundledTax = default(string), System.DateTime? earliestDeliveryDate = default(System.DateTime?), System.DateTime? latestDeliveryDate = default(System.DateTime?), string recommendedAmount = default(string), string eventLocation = default(string), string eventDescription = default(string), System.DateTime? eventDate = default(System.DateTime?), string productType = default(string), string trackingURL = default(string), string terviceType = default(string))
        {
            ItemId = itemId;
            ProductId = productId;
            ConsignmentId = consignmentId;
            BarCodeId = barCodeId;
            TotalCost = totalCost;
            TotalTax = totalTax;
            ItemStatus = itemStatus;
            ItemCode = itemCode;
            ArticleId = articleId;
            ProductName = productName;
            EstimatedDelivery = estimatedDelivery;
            LeavePackage = leavePackage;
            SignatureRequired = signatureRequired;
            TotalBundledCost = totalBundledCost;
            TotalBundledTax = totalBundledTax;
            EarliestDeliveryDate = earliestDeliveryDate;
            LatestDeliveryDate = latestDeliveryDate;
            RecommendedAmount = recommendedAmount;
            EventLocation = eventLocation;
            EventDescription = eventDescription;
            EventDate = eventDate;
            ProductType = productType;
            TrackingURL = trackingURL;
            TerviceType = terviceType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemId")]
        public string ItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public string ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "consignmentId")]
        public string ConsignmentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "barCodeId")]
        public string BarCodeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalCost")]
        public string TotalCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalTax")]
        public string TotalTax { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemStatus")]
        public string ItemStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemCode")]
        public string ItemCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "articleId")]
        public string ArticleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productName")]
        public string ProductName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "estimatedDelivery")]
        public string EstimatedDelivery { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "leavePackage")]
        public string LeavePackage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "signatureRequired")]
        public string SignatureRequired { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalBundledCost")]
        public string TotalBundledCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalBundledTax")]
        public string TotalBundledTax { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "earliestDeliveryDate")]
        public System.DateTime? EarliestDeliveryDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latestDeliveryDate")]
        public System.DateTime? LatestDeliveryDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recommendedAmount")]
        public string RecommendedAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eventLocation")]
        public string EventLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eventDescription")]
        public string EventDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eventDate")]
        public System.DateTime? EventDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productType")]
        public string ProductType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trackingURL")]
        public string TrackingURL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "terviceType")]
        public string TerviceType { get; set; }

    }
}
