// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class StatementDataRow
    {
        /// <summary>
        /// Initializes a new instance of the StatementDataRow class.
        /// </summary>
        public StatementDataRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StatementDataRow class.
        /// </summary>
        public StatementDataRow(string fileName = default(string), byte[] pdfFile = default(byte[]))
        {
            FileName = fileName;
            PdfFile = pdfFile;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "file_name")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pdf_file")]
        public byte[] PdfFile { get; set; }

    }
}
