// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ThreeDSecureDetailsRow
    {
        /// <summary>
        /// Initializes a new instance of the ThreeDSecureDetailsRow class.
        /// </summary>
        public ThreeDSecureDetailsRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ThreeDSecureDetailsRow class.
        /// </summary>
        public ThreeDSecureDetailsRow(bool? enrolled = default(bool?), string authenticated = default(string), string eci = default(string), string xid = default(string), string authenticationValue = default(string), string paReq = default(string), string paRes = default(string), string veReq = default(string), string veRes = default(string))
        {
            Enrolled = enrolled;
            Authenticated = authenticated;
            Eci = eci;
            Xid = xid;
            AuthenticationValue = authenticationValue;
            PaReq = paReq;
            PaRes = paRes;
            VeReq = veReq;
            VeRes = veRes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "enrolled")]
        public bool? Enrolled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authenticated")]
        public string Authenticated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eci")]
        public string Eci { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xid")]
        public string Xid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authenticationValue")]
        public string AuthenticationValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paReq")]
        public string PaReq { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paRes")]
        public string PaRes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "veReq")]
        public string VeReq { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "veRes")]
        public string VeRes { get; set; }

    }
}
