// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Top3MerchantsByTypeRow
    {
        /// <summary>
        /// Initializes a new instance of the Top3MerchantsByTypeRow class.
        /// </summary>
        public Top3MerchantsByTypeRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Top3MerchantsByTypeRow class.
        /// </summary>
        public Top3MerchantsByTypeRow(string mid = default(string), string transactionType = default(string), int? count = default(int?))
        {
            Mid = mid;
            TransactionType = transactionType;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionType")]
        public string TransactionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
