// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransactionVolumeRow
    {
        /// <summary>
        /// Initializes a new instance of the TransactionVolumeRow class.
        /// </summary>
        public TransactionVolumeRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionVolumeRow class.
        /// </summary>
        public TransactionVolumeRow(int? hour = default(int?), int? count = default(int?))
        {
            Hour = hour;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hour")]
        public int? Hour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
