// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransactionBySettlementSummaryRow
    {
        /// <summary>
        /// Initializes a new instance of the TransactionBySettlementSummaryRow
        /// class.
        /// </summary>
        public TransactionBySettlementSummaryRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionBySettlementSummaryRow
        /// class.
        /// </summary>
        public TransactionBySettlementSummaryRow(string globalProperty = default(string), string globalId = default(string), string bank = default(string), string bankId = default(string), string corporate = default(string), string corporateId = default(string), string mid = default(string), string merchantId = default(string), System.DateTime? date = default(System.DateTime?), double? debitTotal = default(double?), double? creditTotal = default(double?), string currency = default(string))
        {
            GlobalProperty = globalProperty;
            GlobalId = globalId;
            Bank = bank;
            BankId = bankId;
            Corporate = corporate;
            CorporateId = corporateId;
            Mid = mid;
            MerchantId = merchantId;
            Date = date;
            DebitTotal = debitTotal;
            CreditTotal = creditTotal;
            Currency = currency;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "global")]
        public string GlobalProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "globalId")]
        public string GlobalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bank")]
        public string Bank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bankId")]
        public string BankId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantId")]
        public string MerchantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "debitTotal")]
        public double? DebitTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creditTotal")]
        public double? CreditTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

    }
}
