// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransactionSuccessFailRow
    {
        /// <summary>
        /// Initializes a new instance of the TransactionSuccessFailRow class.
        /// </summary>
        public TransactionSuccessFailRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionSuccessFailRow class.
        /// </summary>
        public TransactionSuccessFailRow(string productId = default(string), string product = default(string), string merchantId = default(string), string mid = default(string), string corporateId = default(string), string corporate = default(string), System.DateTime? date = default(System.DateTime?), string transactionType = default(string), string paymentMethod = default(string), string cardType = default(string), int? successCount = default(int?), int? failCount = default(int?))
        {
            ProductId = productId;
            Product = product;
            MerchantId = merchantId;
            Mid = mid;
            CorporateId = corporateId;
            Corporate = corporate;
            Date = date;
            TransactionType = transactionType;
            PaymentMethod = paymentMethod;
            CardType = cardType;
            SuccessCount = successCount;
            FailCount = failCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public string ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product")]
        public string Product { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantId")]
        public string MerchantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionType")]
        public string TransactionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethod")]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardType")]
        public string CardType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "successCount")]
        public int? SuccessCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "failCount")]
        public int? FailCount { get; set; }

    }
}
