// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransactionChartRow
    {
        /// <summary>
        /// Initializes a new instance of the TransactionChartRow class.
        /// </summary>
        public TransactionChartRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionChartRow class.
        /// </summary>
        public TransactionChartRow(string transactionType = default(string), int? dayNo = default(int?), string day = default(string), int? count = default(int?))
        {
            TransactionType = transactionType;
            DayNo = dayNo;
            Day = day;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionType")]
        public string TransactionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dayNo")]
        public int? DayNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "day")]
        public string Day { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
