// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransactionManagementResultsRow
    {
        /// <summary>
        /// Initializes a new instance of the TransactionManagementResultsRow
        /// class.
        /// </summary>
        public TransactionManagementResultsRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionManagementResultsRow
        /// class.
        /// </summary>
        public TransactionManagementResultsRow(int? id = default(int?), int? transactionID = default(int?), string apcTransactionID = default(string), string cardExpiryMonth = default(string), string cardExpiryYear = default(string), string cardHolder = default(string), string cardNumber = default(string), string globalId = default(string), string bankID = default(string), string mid = default(string), string product = default(string), string apiId = default(string), string transactionType = default(string), string userID = default(string), string requestorID = default(string), long? amount = default(long?), string channelType = default(string), string currency = default(string), string merchantTxnID = default(string), string paymentMethod = default(string), string cryptoId = default(string))
        {
            Id = id;
            TransactionID = transactionID;
            ApcTransactionID = apcTransactionID;
            CardExpiryMonth = cardExpiryMonth;
            CardExpiryYear = cardExpiryYear;
            CardHolder = cardHolder;
            CardNumber = cardNumber;
            GlobalId = globalId;
            BankID = bankID;
            Mid = mid;
            Product = product;
            ApiId = apiId;
            TransactionType = transactionType;
            UserID = userID;
            RequestorID = requestorID;
            Amount = amount;
            ChannelType = channelType;
            Currency = currency;
            MerchantTxnID = merchantTxnID;
            PaymentMethod = paymentMethod;
            CryptoId = cryptoId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionID")]
        public int? TransactionID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "apcTransactionID")]
        public string ApcTransactionID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardExpiryMonth")]
        public string CardExpiryMonth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardExpiryYear")]
        public string CardExpiryYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardHolder")]
        public string CardHolder { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardNumber")]
        public string CardNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "globalId")]
        public string GlobalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bankID")]
        public string BankID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product")]
        public string Product { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "apiId")]
        public string ApiId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionType")]
        public string TransactionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userID")]
        public string UserID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestorID")]
        public string RequestorID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public long? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "channelType")]
        public string ChannelType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantTxnID")]
        public string MerchantTxnID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethod")]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cryptoId")]
        public string CryptoId { get; set; }

    }
}
