// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Hub.Transactions.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UptimePerformanceIndicatorsRow
    {
        /// <summary>
        /// Initializes a new instance of the UptimePerformanceIndicatorsRow
        /// class.
        /// </summary>
        public UptimePerformanceIndicatorsRow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UptimePerformanceIndicatorsRow
        /// class.
        /// </summary>
        public UptimePerformanceIndicatorsRow(string totalDurationTransaction = default(string), string totalDurationProviders = default(string), string totalDurationAPC = default(string), string corporate = default(string), string corporateId = default(string), string mid = default(string), string merchantId = default(string), string bankId = default(string), string bank = default(string), string globalId = default(string), string globalProperty = default(string))
        {
            TotalDurationTransaction = totalDurationTransaction;
            TotalDurationProviders = totalDurationProviders;
            TotalDurationAPC = totalDurationAPC;
            Corporate = corporate;
            CorporateId = corporateId;
            Mid = mid;
            MerchantId = merchantId;
            BankId = bankId;
            Bank = bank;
            GlobalId = globalId;
            GlobalProperty = globalProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalDurationTransaction")]
        public string TotalDurationTransaction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalDurationProviders")]
        public string TotalDurationProviders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalDurationAPC")]
        public string TotalDurationAPC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporate")]
        public string Corporate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "corporateId")]
        public string CorporateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mid")]
        public string Mid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantId")]
        public string MerchantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bankId")]
        public string BankId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bank")]
        public string Bank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "globalId")]
        public string GlobalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "global")]
        public string GlobalProperty { get; set; }

    }
}
